# Generated by Django 4.2.5 on 2023-10-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_staff_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Notifications',
            new_name='Staff_Notification',
        ),
    ]
