# Generated by Django 4.2.5 on 2023-10-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_attendence_attendence_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
        migrations.RenameModel(
            old_name='Attendence_Report',
            new_name='Attendance_Report',
        ),
    ]
