# Generated by Django 4.2.5 on 2023-10-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_attendence_attendance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendence_date',
            new_name='attendance_date',
        ),
    ]
