# Generated by Django 4.2.5 on 2023-10-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_attendence_date_attendance_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_report',
            old_name='attendence_id',
            new_name='attendance_id',
        ),
    ]
